apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kucc8
  name: kucc8
spec:
  containers:
  - image: nginx
    name: nginx
    imagePullPolicy: IfNotPresent   #如果此 image 已经有了，则不重新下载。考试时写不写都可以。但模拟环境里推荐写，pod 启动快
    resources: {}
  - image: memcached
    name: memcached
    imagePullPolicy: IfNotPresent   #如果此 image 已经有了，则不重新下载。考试时写不写都可以。但模拟环境里推荐写，pod 启动快
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
