apiVersion: v1
kind: Pod
metadata:
  labels:
    run: foo
  name: foo
spec:
  containers:
  - image: nginx
    name: nginx
    imagePullPolicy: IfNotPresent
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
