apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: presentation
  name: presentation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: presentation
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: presentation
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
